"""empty message

Revision ID: 1b385bc299ba
Revises: 9e8bfb09de24
Create Date: 2020-05-25 10:14:01.725427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b385bc299ba'
down_revision = '9e8bfb09de24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_type')
    # ### end Alembic commands ###
