"""empty message

Revision ID: 78a2860876bd
Revises: 1b385bc299ba
Create Date: 2020-05-26 01:34:29.087873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a2860876bd'
down_revision = '1b385bc299ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('probability', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('sentiment', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sentiment')
    op.drop_column('articles', 'probability')
    # ### end Alembic commands ###
